# Generated by Django 3.1.6 on 2021-02-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
