# Generated by Django 3.1.6 on 2021-02-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20210205_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='color',
            field=models.CharField(default='fa5333', max_length=10),
        ),
    ]
