# Generated by Django 3.1.6 on 2021-02-06 13:38

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_dictionary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='color',
            field=colorfield.fields.ColorField(default='#333', max_length=18, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='lang_from',
            field=models.CharField(max_length=100, verbose_name='Language From'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='lang_to',
            field=models.CharField(max_length=100, verbose_name='Language From'),
        ),
    ]
