# Generated by Django 3.1.6 on 2021-02-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_auto_20210206_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='description',
            new_name='definition',
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='color',
            field=models.CharField(default='#fa5333', max_length=9, verbose_name='Color'),
        ),
    ]
