# Generated by Django 3.1.6 on 2021-02-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_auto_20210207_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='lang_from',
            field=models.CharField(choices=[('KA', 'GEORGIAN'), ('EN', 'ENGLISH'), ('RU', 'RUSSIAN')], max_length=100, verbose_name='Language From'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='lang_to',
            field=models.CharField(choices=[('KA', 'GEORGIAN'), ('EN', 'ENGLISH'), ('RU', 'RUSSIAN')], max_length=100, verbose_name='Language To'),
        ),
    ]
