# Generated by Django 3.1.6 on 2021-02-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_auto_20210220_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='lang_from',
            field=models.CharField(max_length=100, verbose_name='Language From'),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='lang_to',
            field=models.CharField(max_length=100, verbose_name='Language To'),
        ),
    ]
