# Generated by Django 3.1.3 on 2021-02-14 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210214_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_type',
        ),
        migrations.AddField(
            model_name='quiz',
            name='words_filter',
            field=models.CharField(choices=[('RN', 'Random'), ('LA', 'New Words'), ('OW', 'Old Words')], default='RN', max_length=255, verbose_name='Words Filter'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_true', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
        ),
    ]
