# Generated by Django 3.1.6 on 2021-02-20 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_auto_20210207_1506'),
        ('quiz', '0004_auto_20210216_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='quiz',
        ),
        migrations.AddField(
            model_name='result',
            name='dictionary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dictionary.dictionary'),
            preserve_default=False,
        ),
    ]
