# Generated by Django 3.1.6 on 2021-02-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210220_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_complete',
        ),
    ]
