# Generated by Django 3.1.6 on 2021-02-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_quiz_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='correct_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='incorrect_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
